### ISSUE TITLE
what is a xxx? includes trailing question mark in definition lookup

### ISSUE THREAD

**Issue by hblack** [DavidGriffith/frotz#18]
Thanks for keeping these awesome games alive.  Here's a very minor issue I found.

### Scenario
Running Zork I from Lost Treasures of Infocom
LinuxUbuntu FrotzV2.43
Typed: "what is a grue?"
### Expected Results
[grue definition]
### Actual Results
I don't know the word "grue?".
### Fault isolation
"what is a grue" returns expected result

**Comment by DavidGriffith** [comment]
I'm not sure if this is a bug in the interpreter or the game code.  I'll do some digging.

**Comment by hblack** [comment]
Should have added, it works in the native DOS client.

**Comment by DavidGriffith** [comment]
Ya.  I just now finished checking various interpreters.  See http://www.intfiction.org/forum/viewtopic.php?f=38&t=18378

**Comment by DavidGriffith** [comment]
I've come to the conclusion that this isn't so much a bug, but a deviation Infocom made from what we now consider the Z-Machine Standard.  That deviation is to truncate the trailing question mark.  They didn't do it with all games.  I'll go through all the Infocom zcode games and see which ones allow questions to be asked of the interpreter, like "WHAT IS A GRUE?" and "WHO IS HOLMES?".  Then for those games I will have Frotz truncate the trailing question mark from input.  Frotz already has several special cases for specific Infocom games, so this shouldn't be too much trouble.

**Comment by DavidGriffith** [comment]
Fixed in 85e0c6e7aa2345622c9c92e0cd6eeb58ab1f88bc
