### ISSUE TITLE
Saving transcripts using dumb frotz (dfrotz)

### ISSUE THREAD

**Issue by thomasboevith** [DavidGriffith/frotz#31]
When I try to save transcripts using the dumb frotz interface (dfrotz) I receive a segmentation fault.

Here is an example of what I am trying to do:

```
>echo "transcript. myfilename. south. quit. yes" | ./dfrotz -S0 -m Advent.z5

Welcome to Adventure!
(Please type HELP for instructions and information.)
.
ADVENTURE
The Interactive Original
By Will Crowther (1976) and Don Woods (1977)
[...]

At End Of Road
You are standing at the end of a road before a small brick building. Around
you is a forest. A small stream flows out of the building and down a gully.
.
At End Of Road                                 Score: 36    Moves: 0
.
> >Please enter a filename [(null)]:
EOT
```

**Comment by DavidGriffith** [comment]
Confirmed, though, what are you intending with that `-m` option?

**Comment by thomasboevith** [comment]
Thanks, the `-m` option I believe is necessary to advance beyond the [MORE] prompt, and thank you for your work on frotz, by the way!

**Comment by DavidGriffith** [comment]
Right.  I was looking at the `ao-curses` branch rather than `master`

**Comment by DavidGriffith** [comment]
Reopening to add to "Pre-2.45 cleanup" milestone
