### ISSUE TITLE
-m parameter for Dumb Frotz not covered in the help menu

### ISSUE THREAD

**Issue by TheSofox** [DavidGriffith/frotz#48]
Dumb Frotz has a -m argument. When used, this skips "MORE" breaks in the text. If you're using dumb frotz on top of such an interface, getting rid of the "MORE" breaks can be very helpfu.

However, for some reason running "dfrotz -h" will not tell you that such an argument exists, I came across it through this forum post: http://www.intfiction.org/forum/viewtopic.php?f=38&t=18125

Repo steps: 
Type in "dfrotz -h" to see the help menu for Dumb Frotz

Expect:
That the help menu would tell you about the -m argument

Actual:
The help menu doesn't mention the -m argument.

Thank you again to all who helped build such a great program as frotz, many fun times using it and I've installed it on so many systems. Really great stuff.

**Comment by DavidGriffith** [comment]
Whoops!

Fixed in e37627bfd376f2e66807304f576554e922406f87
