### ISSUE TITLE
sfrotz wants to build when doing a "make clean"

### ISSUE THREAD

**Issue by DavidGriffith** [DavidGriffith/frotz#73]
@tkorvola Somehow your changes to add sfrotz have resulted in the build process wanting to build sfrotz first before doing a "make clean".  Would you please take a look at this?

**Comment by DavidGriffith** [comment]
I think I fixed it.  The original sfrotz Makefile was doing something weird.  I'll push a fix for this later on today.

**Comment by tkorvola** [comment]
It doesn't compile but it uses the C preprocessor to generate dependency information in `*.d` files, then promptly removes them. I may have found a better way to manage the dependencies, on my (new) misc branch.

**Comment by DavidGriffith** [comment]
It looks good so far!  I like the commit concerning keeping sound options from leaking to other interface libraries.  Last night / this morning, I tried to fold in the sfrotz Makefile contents into the main Makefile, and then I realized the compile options leak problem.  I managed to fix some of it, but all of it was unfixable.  So I went with giving the core, blorb, and interface directories their own Makefiles, which WOULD allow this to work.

**Comment by DavidGriffith** [comment]
I see.  I got on this because the not-compile would balk whenever any of the generated headers were not present.

**Comment by tkorvola** [comment]
Problem solved: sfrotz no longer includes any generated headers. Header file generation should really avoid touching the result file if it has not changed. However, a different solution was needed for the ever-changing build time stamp.

Also, the new sdl/Makefile makes no separate effort to generate dependencies. They are produced as a side effect of compilation by the rule for creating object files, in particular only if those object files are required.

**Comment by DavidGriffith** [comment]
Nice.  I look forward to seeing your pull request.
